### ISSUE TITLE
jsoneditoronline

### ISSUE THREAD

**Issue by ranlandau** [DefinitelyTyped/DefinitelyTyped#10864]
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.

ive added the package from npm

my ts file
import { JSONEditor } from '@types/jsoneditoronline';

error:
client/components/viewObject/viewObject.component.ts(9,28): error TS2306: File 'D:/src/portal/node_modules/@types/jsoneditoronline/index.d.ts' is not a module.

**Comment by alejo90** [comment]
`@types/jsoneditoronline` is a typing definition that gives the compiler enough information about a package to verify your code. You need to install both the typing definition and the real package. Then, in your ts file, just import the real package `import { JSONEditor } from 'jsoneditoronline';`

**Comment by ranlandau** [comment]
Maybe something is missing?

import { JSONEditor } from 'jsoneditor';
client/components/viewObject/viewObject.component.ts(10,28): error TS2307: Cannot find module 'jsoneditor'.

package.json
"@types/jsoneditoronline": "0.0.27",
  "jsoneditor": "^5.5.7",

**Comment by alejo90** [comment]
I just looked at the definition and it wasn't created with module declarations for use in imports. For now, you can't use the typing definition as it is. On the meantime, the easiest solution is that you create your own typing in a `jsoneditor.d.ts` file in your project's sources:

```
declare module 'jsoneditor' {
 export const JSONEditor: any;
}
```

It won't provide intellisense, but it will get your stuff to compile. I'll submit a pull request fixing the main typing and reference it here.

**Comment by ranlandau** [comment]
Thanks for the help
It's compilng now, but still fails on evaluting for some reason
i'll wait for your push or anothjer tip!

Thanks alot.

**Comment by alejo90** [comment]
Glad I could help. Is it failing at runtime?

**Comment by ranlandau** [comment]
Yes - again thanks alot!

It's failing in the browser (chrome debug output)

Error: SyntaxError: Unexpected token <
at Object.eval (http://localhost:3000/client/components/viewObject/viewObject.component.js:18:20)
at eval (http://localhost:3000/client/components/viewObject/viewObject.component.js:61:4)
at eval (http://localhost:3000/client/components/viewObject/viewObject.component.js:62:3)
Evaluating http://localhost:3000/jsoneditor
Evaluating http://localhost:3000/client/components/viewObject/viewObject.component.js
Evaluating http://localhost:3000/client/routes.js
Evaluating http://localhost:3000/client/main.js
Error loading http://localhost:3000/client/main.js

**Comment by alejo90** [comment]
Oh, this is something different. Go to that line in the output and take a look at the generated js.

**Comment by ranlandau** [comment]
Line 18:
var jsoneditor_1 = require('jsoneditor');

  var editor = new jsoneditor_1.JSONEditor(container, { mode: "view" });
            //console.log(JSONEditor);
            editor.set(data.result);

**Comment by alejo90** [comment]
I think that means you're not passing valid json to the editor in `editor.set(data.result)`.

**Comment by ranlandau** [comment]
It happens also when I remove that line of code

**Comment by ranlandau** [comment]
Or console logging the require obj

**Comment by alejo90** [comment]
Wait a minute. The code that's actually running (`http://localhost:3000/client/components/viewObject/viewObject.component.js:18:20`) contains that `require`? Are you using a tool like browserify or webpack? What module configuration option are you passing to the compiler (directly on in `tsconfig.json`)?

**Comment by ranlandau** [comment]
i use nodemon - but i can use pure express also
and yes, like 18 in my js file is the require
var jsoneditor_1 = require('jsoneditor');

this is my tsconfig

{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "baseUrl": ".",
        "paths": {
            "components/*": [
                "client/components/*"
            ],
            "services/*": [
                "client/service/*"
            ]
        }
    },
    "exclude": [
        "../node_modules",
        "node_modules"
    ]     
}

**Comment by alejo90** [comment]
The module setting is the problem. You're compiling as if to run in node.js and not in the browser. At the moment I can't really tell you what the module setting needs to be when using vanilla typescript because I always bundle using webpack.

**Comment by alejo90** [comment]
PR: #10870

**Comment by ranlandau** [comment]
Wow!
Thanks alot

but when i'm using the file you use
i get
client/components/viewObject/viewObject.component.ts(11,10): error TS2305: Module ''jsoneditor'' has no exported member 'JSONEditor'.

**Comment by alejo90** [comment]
Use `import JSONEditor from 'jsoneditor';`
