### ISSUE TITLE
[Req|Bug] Update webpack type defs for BannerPlugin

### ISSUE THREAD

**Issue by luchillo17** [DefinitelyTyped/DefinitelyTyped#14304]
- [x] I tried using the `@types/webpack@2.2.4` package and had problems.
  - Authors: @mattlewis92, @bumbleblym, @bcherny

So i was using latest webpack (2.2.0 at the moment) and trying to use the `BannerPlugin`, however ts-node (used by webpack 2 to run config files made in typescript) complains for the arguments of the plugin, while the plugin itself complains because in Webpack 2 it requests a single argument.

Basically the type defs are outdated, they still expect Webpack 1 plugin args version, here are the 2 errors, first the one by the linter (caused by the type defs):

```sh
/usr/local/lib/node_modules/ts-node/src/index.ts:312
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
config/webpack.common.ts (157,7): Supplied parameters do not match any signature of call target. (2346)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:312:17)
    at /usr/local/lib/node_modules/ts-node/src/index.ts:343:18
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:476:19)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:406:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

The next one is the actual plugin complaining because in Webpack 2 it expects a single arg (breaking change from Webpack 1 to 2):
```sh
/Users/aplicaciones2/Documents/tao-graphql-api/node_modules/webpack/lib/BannerPlugin.js:19
			throw new Error("BannerPlugin only takes one argument (pass an options object)");
         ^
Error: BannerPlugin only takes one argument (pass an options object)
    at new BannerPlugin (/Users/aplicaciones2/Documents/tao-graphql-api/node_modules/webpack/lib/BannerPlugin.js:19:10)
    at module.exports (/Users/aplicaciones2/Documents/tao-graphql-api/config/webpack.common.ts:134:13)
    at Object.<anonymous> (/Users/aplicaciones2/Documents/tao-graphql-api/config/webpack.dev.ts:19:29)
    at Module._compile (module.js:570:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:406:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by bcherny** [comment]
@Luchillo Give putting up a PR yourself a shot - it's super easy:

1. Fork this repo
2. Edit the webpack typings
3. Edit the webpack typings tests (easy way to make sure your typings are right)
4. Make sure tests pass (`npm test`)
5. Make a pull request

**Comment by Luchillo** [comment]
In such case should i add myself to the Authors list?

**Comment by Luchillo** [comment]
For now my best fix is this:
```ts
const BannerPlugin: (options: any) => Plugin = webpack.BannerPlugin as any;
```

**Comment by bcherny** [comment]
> In such case should i add myself to the Authors list?

Yes!

> Also a little lost in how to edit the tests, i don't see any package.json neither in the webpack typedef folder, nor in the root of repo.

Look for [webpack-tests.ts](https://github.com/mohsen1/DefinitelyTyped/blob/types-2.0/webpack/webpack-tests.ts).

> For now my best fix is this

Can you avoid the `any`s, and add more specific types for `options`?

**Comment by Luchillo** [comment]
> Yes!
Coool

> Look for webpack-tests.ts.
I did before, but i don't see where's the package.json that would allow me to execute `npm test`.

> Can you avoid the anys, and add more specific types for options?
I can, however i'll have to look at the plugin readme, the options in the current type definition for that plugin already uses `any`, that's why i use `any`, besides is just a little hack to stop types from complaining since i know its working without the types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
