### ISSUE TITLE
@types/requirejs  Variable 'require' must be of type 'NodeRequire'

### ISSUE THREAD

**Issue by cyandream** [DefinitelyTyped/DefinitelyTyped#15851]
- [X] I tried using the `@types/requirejs` package and had problems.
    Error from console:
```
node_modules/@types/requirejs/index.d.ts
(416,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.

```
typescript error - 

in @types/requirejs/index.d.ts 
ln416    **declare var require: Require;**

And in @types/node/index.d.ts
ln73    **declare var require: NodeRequire;**

Thanks

Michelle

- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

**Comment by ETE-Jens-Ihrig** [comment]
Same Problem here with error message with different order:
node_modules/@types/webpack-env/index.d.ts
`Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.`

And node_modules/@types/node/index.d.ts
` error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.
`

**Comment by e-cloud** [comment]
see a may-be solution here https://medium.com/@mindginative/typescript-its-magic-number-ts2403-ef76202185c9

**Comment by kumaresan-subramani** [comment]
i am also facing same problem. this breaks my entire application

> [11:20:44] D:/workspace/components/ej2-button-components/node_modules/@types/requirejs/index.d.ts(421)
>  Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.
> Rendering [========================================] 100%
> [11:20:46] Finished 'typedoc' after 12 s
> [11:20:46] Finished 'execute-generator' after 12 s
> [11:20:46] Starting 'scripts'...
> [11:20:46] Starting 'scripts-gen'...
> D:/workspace/components/ej2-button-components/node_modules/@types/requirejs/index.d.ts(422,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.
> [11:20:58] 'scripts-gen' errored after 12 s
> [11:20:58] TypeScript error: D:/workspace/components/ej2-button-components/node_modules/@types/requirejs/index.d.ts(422,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.
>     at Object.getError (D:\workspace\components\ej2-button-components\node_modules\gulp-typescript\release\utils.js:53:15)
>     at Output.getError (D:\workspace\components\ej2-button-components\node_modules\gulp-typescript\release\output.js:224:22)
>     at Output.diagnostic (D:\workspace\components\ej2-button-components\node_modules\gulp-typescript\release\output.js:227:25)
>     at ProjectCompiler.inputDone (D:\workspace\components\ej2-button-components\node_modules\gulp-typescript\release\compiler.js:69:33)
>     at CompileStream.end (D:\workspace\components\ej2-button-components\node_modules\gulp-typescript\release\main.js:62:31)
>     at DestroyableTransform.onend (D:\workspace\components\ej2-button-components\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
>     at Object.onceWrapper (events.js:313:30)
>     at emitNone (events.js:111:20)
>     at DestroyableTransform.emit (events.js:208:7)
>     at D:\workspace\components\ej2-button-components\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
> [11:20:58] 'build' errored after 24 s
> [11:20:58] TypeScript error in plugin 'run-sequence(scripts-gen)'

**Please provide any workaround for this**

**Comment by kumaresan-subramani** [comment]
same problem https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31628

**Comment by abhinavsingh** [comment]
Anyone visiting this after years :) Here is what we observed.

1. We are building a project for browser
2. But also using `mocha` without testing in browser
3. This required us to install `ts-node` and `amd-loader`
4. Unfortunately, installing these deps started resulting in built errors.
