### ISSUE TITLE
Error trying to run lint for a new type

### ISSUE THREAD

**Issue by AlexTeixeira** [DefinitelyTyped/DefinitelyTyped#17393]
Hello,

I'm not sure if I should post here, but otherwise it's related to this repo.

I'm trying to create a typing for my plugin wrote in TypeScript.
 To achieve this I'm following the instructions in the **Readme** of this repo.

When I try to `run npm run lint askmethat-rating` to test my typing, I have some **TsLint errors** ( that look strange from my point of view ) and I got a **npm error** after the list of **TsLint errors**.

**Here the console output :** 

![nodeerror1](https://user-images.githubusercontent.com/6555080/27439071-43546948-5767-11e7-8861-78d2666142fa.PNG)

**And here the log output :** 

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Tools\\nodejs\\node.exe',
1 verbose cli   'D:\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint',
1 verbose cli   'askmethat-rating' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle definitely-typed@0.0.1~prelint: definitely-typed@0.0.1
6 silly lifecycle definitely-typed@0.0.1~prelint: no script for prelint, continuing
7 info lifecycle definitely-typed@0.0.1~lint: definitely-typed@0.0.1
8 verbose lifecycle definitely-typed@0.0.1~lint: unsafe-perm in lifecycle true
9 verbose lifecycle definitely-typed@0.0.1~lint: PATH: D:\Tools\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Dev\OpenSource\DefinitelyTyped\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;D:\Tools\Git\cmd;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\ProgramData\chocolatey\bin;D:\Tools\nodejs\;C:\Program Files (x86)\GtkSharp\2.12\bin;D:\Tools\Yarn\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\Tools\Ruby24-x64\bin;C:\Users\alexa\AppData\Local\Microsoft\WindowsApps;;D:\IDE\Microsoft VS Code\bin;C:\Users\alexa\AppData\Roaming\npm;C:\Users\alexa\AppData\Local\Yarn\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\
10 verbose lifecycle definitely-typed@0.0.1~lint: CWD: D:\Dev\OpenSource\DefinitelyTyped
11 silly lifecycle definitely-typed@0.0.1~lint: Args: [ '/d /s /c', 'dtslint types "askmethat-rating"' ]
12 silly lifecycle definitely-typed@0.0.1~lint: Returned: code: 1  signal: null
13 info lifecycle definitely-typed@0.0.1~lint: Failed to exec lint script
14 verbose stack Error: definitely-typed@0.0.1 lint: `dtslint types "askmethat-rating"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Tools\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Tools\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid definitely-typed@0.0.1
16 verbose cwd D:\Dev\OpenSource\DefinitelyTyped
17 verbose Windows_NT 10.0.15063
18 verbose argv "D:\\Tools\\nodejs\\node.exe" "D:\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint" "askmethat-rating"
19 verbose node v8.1.2
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error definitely-typed@0.0.1 lint: `dtslint types "askmethat-rating"`
23 error Exit status 1
24 error Failed at the definitely-typed@0.0.1 lint script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

If you need the code of my definition just ask me.

Thanks for your help.

**Comment by AlexTeixeira** [comment]
close
