### ISSUE TITLE
 Error: Cannot find module 'locutus/php'

### ISSUE THREAD

**Issue by booradleys** [DefinitelyTyped/DefinitelyTyped#17752]
- [x] I tried using the `@types/locutus` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by: Hookclaw <https://github.com/hookclaw>` 
  - Authors: @Hookclaw 
````
> npm install @types/node --save
> npm install @types/locutus -- save
> gulp (OK no warning)
> node app.ts
````
 => Error: Cannot find module 'locutus/php' in ProvinceRepository
``
C:\Applications\Node\exotica\server>node app.js
{ Error: Cannot find module 'locutus/php'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Applications\Node\exotica\server\dist\repository\ProvinceRepository.js:12:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
``

ProvinceRepository :
````
...
import * as locutus from "locutus/php";
...
````
**I see that directory ``/node_modules/@types/locutus`` exists but
``/node_modules/locutus`` doesn't !**

I don't know how to resolve this issue.
Can anyone help me ?

**Comment by booradleys** [comment]
Issue resolved by doing:
``
>npm install locutus --save
``
So i definitely don't understand utility of DefinitelyTyped.
