### ISSUE TITLE
twilio types v0.0.9 is not compatible with twilio sdk 3.6.2

### ISSUE THREAD

**Issue by nguyeda** [DefinitelyTyped/DefinitelyTyped#18992]
- [x] I tried using the `@types/twilio` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nickiannone, @ashleybrener

Hi Guys,

I've been trying to get the twilio sdk 3.6.2 to work with typescript and it seems the last version of @types/twilio (v0.0.9) is not compatible. The following snippet works fine with twilio sdk 2.1.1 but gives some errors on 3.6.2:

```
const restClient = new twilio.RestClient(twilioConfig.sid, twilioConfig.token);

restClient.availablePhoneNumbers('US').local.get({
  areaCode:'651'
}).then(res => console.log(JSON.stringify(res)));

const twiml = new twilio.TwimlResponse();
twiml.say('hello world');
console.log(twiml.toString());
```

errors:
```
const restClient = new twilio.RestClient(twilioConfig.sid, twilioConfig.token);
                   ^
TypeError: twilio.RestClient is not a constructor
    at Object.<anonymous> (/.../index.ts)
    at Module._compile (module.js:570:32)
    at Module.m._compile (/.../node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] ([...]/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```
and:
```
const twiml = new twilio.TwimlResponse();
              ^
TypeError: twilio.TwimlResponse is not a constructor
    at Object.<anonymous> (/.../index.ts)
    at Module._compile (module.js:570:32)
    at Module.m._compile (/.../node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/.../node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

Is there any plan to add support for 3.x? I'd love to help but I'm too much of a noob at typescript and javascript to do anything useful.

**Comment by dharsanav** [comment]
I have a similar issue while creating new Twilio Instance.However Iam not getting any error. Also the **fetch()** method as shown in 
```
client.messages('SM123')
 .fetch(function(err, message) {
  console.log(message.sid); //=> SM123
});
```
(Code from https://www.twilio.com/docs/libraries/node/migration-guide#accessing-resources ) is not available.It would be nice to have support for 3.x.

**Comment by cruhl** [comment]
I'm having the same issue since TwimlResponse is now VoiceResponse...

**Comment by omidkrad** [comment]
related: https://github.com/twilio/twilio-node/issues/250#issuecomment-360680866

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
