### ISSUE TITLE
Build Error: 'Map' is not exported by node

### ISSUE THREAD

**Issue by YichenMao** [DefinitelyTyped/DefinitelyTyped#21196]
Hello Alejandro and Arne,
   I tried to create a map module with functional component, which could be reuse later by npm install.  Inside this project, I imported the @type/leaflet library and use the classes inside there:
` import {Map} from 'leaflet';`
These typescript classes work perfect in this own project. However, when ever I try to build and publish it to npm, it getting the Build Error:

`'Map' is not exported by node_modules\leaflet\dist\leaflet-src.js
Error: 'Map' is not exported by node_modules\leaflet\dist\leaflet-src.js
    at error (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:8390:3)
    at Module.trace (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:8487:10)
    at ModuleScope.findVariable (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:8093:22)
    at Scope.findVariable (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:6183:33)
    at FunctionScope.findVariable (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:6183:33)
    at Scope.findVariable (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:6183:33)
    at Identifier.bind (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:6996:31)
    at eachChild.child (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:5819:34)
    at keys.forEach.key (D:\Development\schlothauer-wauer\generic-map\sw-map-module\node_modules\rollup\dist\rollup.js:5847:5)`

  - Authors: @alejo90 @atd-schubert 

If you know how I could solve this exporting issue?
Thank you very much in advanced!

**Comment by atd-schubert** [comment]
@YichenMao I don't have problems with importing the `Map` class of leaflet.

When I take a look at the library information (`npm info @types/leaflet`) I see that the old version `0.7.*` is marked as latest version at the moment. Try to specify the "real" latest version during installation, like this:

```bash
npm install --save leaflet@latest @types/leaflet@1.2.*
```

In addition we made some changes to the type definition of leaflet that need version 2.3 and above of TypeScript. See #21218 for further information...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
