### ISSUE TITLE
@types/geojson breaks Ionic 2 with latest commit

### ISSUE THREAD

**Issue by brandonmarino** [DefinitelyTyped/DefinitelyTyped#21281]
commit [216ea71] has caused cordova transpile to fail. Reverted back to the previous version of that file and it worked fine

Running app-scripts build: --platform android --target cordova
[11:52:02]  build dev started ... 
[11:52:02]  clean started ... 
[11:52:02]  clean finished in 1 ms 
[11:52:02]  copy started ... 
[11:52:02]  transpile started ... 
[11:52:07]  typescript: node_modules/@types/geojson/index.d.ts, line: 94 
            ',' expected. 

      L94:  /***
      L95:   * http://geojson.org/geojson-spec.html#feature-collection-objects

[11:52:07]  typescript: node_modules/@types/geojson/index.d.ts, line: 104 
            ',' expected. 

     L103:   * http://geojson.org/geojson-spec.html#coordinate-reference-system-objects
     L105:  export interface CoordinateReferenceSystem {

[11:52:07]  typescript: node_modules/@types/geojson/index.d.ts, line: 94 
            Type parameter name cannot be 'any' 

      L94:  /***
      L95:   * http://geojson.org/geojson-spec.html#feature-collection-objects

[11:52:07]  typescript: node_modules/@types/geojson/index.d.ts, line: 104 
            Type parameter name cannot be 'any' 

     L103:   * http://geojson.org/geojson-spec.html#coordinate-reference-system-objects
     L105:  export interface CoordinateReferenceSystem {

[11:52:07]  typescript: node_modules/@types/geojson/index.d.ts, line: 106 
            Generic type 'Feature<G, P, any>' requires 3 type argument(s). 

     L105:  export interface CoordinateReferenceSystem {
                type: string;
     L107:      properties: any;

Error: Failed to transpile program
    at new BuildError (/Users/brandonmarino/Projects/dTIMS%20GO/dTIMS-GO/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /Users/brandonmarino/Projects/dTIMS%20GO/dTIMS-GO/node_modules/@ionic/app-scripts/dist/transpile.js:137:20
    at new Promise (<anonymous>)
    at transpileWorker (/Users/brandonmarino/Projects/dTIMS%20GO/dTIMS-GO/node_modules/@ionic/app-scripts/dist/transpile.js:103:12)
    at Object.transpile (/Users/brandonmarino/Projects/dTIMS%20GO/dTIMS-GO/node_modules/@ionic/app-scripts/dist/transpile.js:61:12)
    at buildProject (/Users/brandonmarino/Projects/dTIMS%20GO/dTIMS-GO/node_modules/@ionic/app-scripts/dist/build.js:97:78)
    at /Users/brandonmarino/Projects/dTIMS%20GO/dTIMS-GO/node_modules/@ionic/app-scripts/dist/build.js:47:16
    at <anonymous>

**Comment by brandonmarino** [comment]
This was due to using an older version of cordova-cli. Works on the most recent version fine. Sorry about that.
