### ISSUE TITLE
Request-ip typings incompatible with express typings.

### ISSUE THREAD

**Issue by westy92** [DefinitelyTyped/DefinitelyTyped#21524]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MrHen 

[`request-ip`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/df1045bb86cf3b38f7717ac3c98d920a91b30882/types/request-ip/index.d.ts) should be using the `express` typings, instead of defining its own [`Request`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/df1045bb86cf3b38f7717ac3c98d920a91b30882/types/request-ip/index.d.ts#L21) interface.

With TypeScript 2.6.1 I'm getting the following error:
```
TypeScript error: src/middleware/rate-limit.ts(38,59): error TS2345: Argument of type 'e.Request' is not assignable to parameter of type 'Request'.
  Types of property 'headers' are incompatible.
    Type 'IncomingHttpHeaders' has no properties in common with type '{ 'x-client-ip'?: string; 'x-forwarded-for'?: string; 'x-real-ip'?: string; 'x-cluster-client-ip'...'.
    at Object.getError (/home/seth/Source/api/node_modules/gulp-typescript/release/utils.js:56:15)
    at Output.getError (/home/seth/Source/api/node_modules/gulp-typescript/release/output.js:92:22)
    at Output.diagnostic (/home/seth/Source/api/node_modules/gulp-typescript/release/output.js:95:25)
    at ProjectCompiler.reportDiagnostics (/home/seth/Source/api/node_modules/gulp-typescript/release/compiler.js:144:33)
    at ProjectCompiler.inputDone (/home/seth/Source/api/node_modules/gulp-typescript/release/compiler.js:43:38)
    at CompileStream.end (/home/seth/Source/api/node_modules/gulp-typescript/release/project.js:136:31)
    at DestroyableTransform.onend (/home/seth/Source/api/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
```

**Comment by westy92** [comment]
I realized there was an update to `@types/request-ip`.  This issue is gone in the latest version.
