### ISSUE TITLE
error TS4053: Return type of public method from exported class has or is using name 'GridFSBucketReadStream' from external module 

### ISSUE THREAD

**Issue by txiaocao** [DefinitelyTyped/DefinitelyTyped#21638]
-  I tried using the `@types/mongodb` package and had problems.
-  I tried using the latest stable version of tsc. 2.3.0

```
tsc -p src 
src/server/libs/phantomjs/H5Capture.ts(74,18): error TS4053: Return type of public method from exported class has or is using name 'GridFSBucketReadStream' from external module "C:/disk0/repository/kemao/kemao-node-basis/web-spider/node_modules/@types/mongodb/index" but cannot be named.

    at r.<anonymous> (C:\disk0\repository\kemao\kemao-node-basis\web-spider\node_modules\@kemao-node-basis\package-tools\libs\ShellHelper.js:1:1295)
    at step (C:\disk0\repository\kemao\kemao-node-basis\web-spider\node_modules\tslib\tslib.js:129:27)
    at Object.next (C:\disk0\repository\kemao\kemao-node-basis\web-spider\node_modules\tslib\tslib.js:110:57)
    at C:\disk0\repository\kemao\kemao-node-basis\web-spider\node_modules\tslib\tslib.js:103:75
```

```
[ts] Return type of public method from exported class has or is using name 'GridFSBucketReadStream' from external module "c:/disk0/repository/kemao/kemao-node-basis/web-spider/node_modules/@types/mongodb/index" but cannot be named.
(method) H5Capture.getBucketReadStream(url: any): Promise<GridFSBucketReadStream>

public async getBucketReadStream(url) {
        const db = await mongoDatabase.getDB("web-spider");
        const screenshots = db.collection("screenshots");
        const record = await screenshots.findOne({ url });
        logger.log("view", record);
        const bucket = new GridFSBucket(db, { bucketName: "screenshots" });
        const stream = bucket.openDownloadStreamByName(record.screenshot);
        return stream;
}
```

**Comment by txiaocao** [comment]
I add the method type，and this problem resolve... I think this is typescript type deduction bug?
```
public async getBucketReadStream(url: string): Promise<GridFSBucketReadStream> 
```

**Comment by DevEarley** [comment]
`public async getBucketReadStream(url: string): any { ... } `
should work too.  _Strangely_ this only happens when the method was marked public, if i make it private - no issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
