### ISSUE TITLE
confirmdialog depends on jquery but has a lower required TypeScript version.

### ISSUE THREAD

**Issue by allipierre** [DefinitelyTyped/DefinitelyTyped#21709]
After run npm test localy i have that error

:DefinitelyTyped user$ npm test

> definitely-typed@0.0.1 test /Users/yotti/nodejs/DefinitelyTyped
> node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed

`**Error: confirmdialog depends on jquery but has a lower required TypeScript version.**`
    at checkTypeScriptVersions (/Users/yotti/nodejs/DefinitelyTyped/node_modules/types-publisher/src/check-parse-results.ts:59:11)
    at Object.<anonymous> (/Users/yotti/nodejs/DefinitelyTyped/node_modules/types-publisher/src/check-parse-results.ts:17:2)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/yotti/nodejs/DefinitelyTyped/node_modules/types-publisher/bin/check-parse-results.js:4:58)
    at <anonymous>
npm ERR! Test failed.  See above for more details.

i have Import jquery like so /// <reference types="jquery"/>

Thanks

**Comment by joeskeen** [comment]
@allipierre did you ever resolve your issue? I have been getting the same error message for another package and I'm not sure how to resolve it.

**Comment by joeskeen** [comment]
I figured out the issue.  The file needs to have this line (and is case-sensitive):

```ts
// TypeScript Version: 2.3
```

**Comment by allipierre** [comment]
Yes i resolve it like so too
