### ISSUE TITLE
import error in @types/pubnub

### ISSUE THREAD

**Issue by m0a** [DefinitelyTyped/DefinitelyTyped#22186]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/pubnub` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bitbankinc

write this code 

```
import PubNub from 'pubnub'

const pubnub = new PubNub({subscribeKey: 'sub-c-52a9ab50-291b-11e5-baaa-0619f8945a4f'});
pubnub.addListener({
	message: (message) => {
		console.log(message);
	}
});

pubnub.subscribe({
	channels: ['lightning_ticker_BTC_JPY']
})

```

but error occured.

```
ts-node src/index.ts                                                                                                                                                                                [23:36:41]
TypeError: pubnub_1.default is not a constructor
    at /Users/m0a/repo/bitbucket.org/m0a/bitFlyerBot/src/index.ts:4:16
    at Object.defineProperty.value (/Users/m0a/repo/bitbucket.org/m0a/bitFlyerBot/src/index.ts:3:17)
    at Object.<anonymous> (/Users/m0a/repo/bitbucket.org/m0a/bitFlyerBot/src/index.ts:9:3)
    at Module._compile (module.js:624:30)
    at Module.m._compile (/Users/m0a/.anyenv/envs/ndenv/versions/v8.5.0/lib/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/m0a/.anyenv/envs/ndenv/versions/v8.5.0/lib/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

so  change code in @types/pubnub/index.d.ts

from 

```
export default Pubnub;
```

to

```
export = Pubnub
```

it's works!

**Comment by soulmachine** [comment]
I have the same issue here, the class and namespace both have the same name "PubNub", I think this is the reason, I don't know how to solve it yet, for now I have to modify the `index.d.ts` as above
