### ISSUE TITLE
Cannot create package with uppercase letters

### ISSUE THREAD

**Issue by NN---** [DefinitelyTyped/DefinitelyTyped#22745]
There are two packages with the same name but different case:

https://www.npmjs.com/package/JSON2
https://www.npmjs.com/package/json2

I would like to create a package for JSON2 and I cannot do it due to:

```
Error: Package name `JSON2` should be strictly lowercase
    at Object.<anonymous> (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:18:9)
    at Generator.next (<anonymous>)
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:3:12)
    at Object.getTypingInfo (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:20:12)
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser-worker.ts:29:22
    at Generator.next (<anonymous>)
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser-worker.js:7:71
    at new Promise (<anonymous>)
Error: Parsing failed.
    at fail (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:320:11)
    at ChildProcess.child.on (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:308:6)
    at emitNone (events.js:106:13)
    at ChildProcess.emit (events.js:208:7)
    at finish (internal/child_process.js:757:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by NN---** [comment]
Workaround using https://www.npmjs.com/package/json-js
