### ISSUE TITLE
@types/react-leaflet, @types/react-router fail to lint against typescript@next

### ISSUE THREAD

**Issue by craigkovatch** [DefinitelyTyped/DefinitelyTyped#22788]
**types/react-leaflet authors:**
@danzel @davschne @yuit

**types/react-router authors:**
@sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @tkrotoff @huy-nguyen @grmiade @DaIgeb @egorshulga

`npm test` on master is failing. It appears that the prerelease next version of tsc has issues against these two packages.

```
=== ERRORS ===
Error in react-leaflet
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-leaflet/react-leaflet-tests.tsx
ERROR: 351:32  expect  TypeScript@next compile error: 
Type '{ children: Element[]; position: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<LayersControl<LayersControlProps, Layers>> & Reado...'.
  Type '{ children: Element[]; position: string; }' is not assignable to type 'Readonly<LayersControlProps>'.
    Types of property 'position' are incompatible.
      Type 'string' is not assignable to type '"topleft" | "topright" | "bottomleft" | "bottomright" | undefined'.
ERROR: 568:30  expect  TypeScript@next compile error: 
Type '{ children: Element; direction: string; offset: number[]; opacity: number; permanent: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Tooltip<TooltipProps, Tooltip>> & Readonly<{ child...'.
  Type '{ children: Element; direction: string; offset: number[]; opacity: number; permanent: true; }' is not assignable to type 'Readonly<TooltipProps>'.
    Types of property 'offset' are incompatible.
      Type 'number[]' is not assignable to type '[number, number] | Point | undefined'.
        Type 'number[]' is not assignable to type 'Point'.
          Property 'clone' is missing in type 'number[]'.
ERROR: 656:17  expect  TypeScript@next compile error: 
Type '{ children: Element[]; center: number[]; zoom: number; onclick: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Map<MapProps, Map>> & Readonly<{ children?: ReactN...'.
  Type '{ children: Element[]; center: number[]; zoom: number; onclick: () => void; }' is not assignable to type 'Readonly<MapProps>'.
    Types of property 'center' are incompatible.
      Type 'number[]' is not assignable to type 'LatLng | LatLngLiteral | [number, number] | undefined'.
        Type 'number[]' is not assignable to type '[number, number]'.
          Property '0' is missing in type 'number[]'.
ERROR: 675:10  expect  TypeScript@next compile error: 
Type '{ children: Element[]; center: number[]; zoom: number; zoomControl: boolean; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Map<MapProps, Map>> & Readonly<{ children?: ReactN...'.
  Type '{ children: Element[]; center: number[]; zoom: number; zoomControl: boolean; }' is not assignable to type 'Readonly<MapProps>'.
    Types of property 'center' are incompatible.
      Type 'number[]' is not assignable to type 'LatLng | LatLngLiteral | [number, number] | undefined'.
        Type 'number[]' is not assignable to type '[number, number]'.
ERROR: 680:22  expect  TypeScript@next compile error: 
Type '{ position: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ZoomControl<ZoomOptions, Zoom>> & Readonly<{ child...'.
  Type '{ position: string; }' is not assignable to type 'Readonly<ZoomOptions>'.
    Types of property 'position' are incompatible.
      Type 'string' is not assignable to type '"topleft" | "topright" | "bottomleft" | "bottomright" | undefined'.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:101:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
Error in react-router
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-router/test/examples-from-react-router-website/Animation.tsx
ERROR: 25:23  expect  TypeScript@next compile error: 
Binding element 'location' implicitly has an 'any' type.
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-router/test/examples-from-react-router-website/Auth.tsx
ERROR: 58:28  expect  TypeScript@next compile error: 
Parameter 'props' implicitly has an 'any' type.
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-router/test/examples-from-react-router-website/CustomLink.tsx
ERROR: 27:71  expect  TypeScript@next compile error: 
Binding element 'match' implicitly has an 'any' type.
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-router/test/examples-from-react-router-website/RouteConfig.tsx
ERROR: 67:36  expect  TypeScript@next compile error: 
Parameter 'props' implicitly has an 'any' type.
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-router/test/examples-from-react-router-website/StaticRouter.tsx
ERROR: 14:9   expect  TypeScript@next compile error: 
Type '{ render: ({ staticContext }: { staticContext: any; }) => Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Route<RouteProps>> & Readonly<{ children?: ReactNo...'.
  Type '{ render: ({ staticContext }: { staticContext: any; }) => Element; }' is not assignable to type 'Readonly<RouteProps>'.
    Types of property 'render' are incompatible.
      Type '({ staticContext }: { staticContext: any; }) => Element' is not assignable to type '((props: RouteComponentProps<any>) => ReactNode) | undefined'.
        Type '({ staticContext }: { staticContext: any; }) => Element' is not assignable to type '(props: RouteComponentProps<any>) => ReactNode'.
ERROR: 14:9   expect  TypeScript@next compile error: 
Type '{ render: ({ staticContext }: { staticContext: any; }) => Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Route<RouteProps>> & Readonly<{ children?: ReactNo...'.
  Type '{ render: ({ staticContext }: { staticContext: any; }) => Element; }' is not assignable to type 'Readonly<RouteProps>'.
    Types of property 'render' are incompatible.
      Type '({ staticContext }: { staticContext: any; }) => Element' is not assignable to type '((props: RouteComponentProps<any>) => ReactNode) | undefined'.
        Type '({ staticContext }: { staticContext: any; }) => Element' is not assignable to type '(props: RouteComponentProps<any>) => ReactNode'.
          Types of parameters '__0' and 'props' are incompatible.
            Type 'RouteComponentProps<any>' is not assignable to type '{ staticContext: any; }'.
              Property 'staticContext' is optional in type 'RouteComponentProps<any>' but required in type '{ staticContext: any; }'.
ERROR: 14:20  expect  TypeScript@next compile error: 
Binding element 'staticContext' implicitly has an 'any' type.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:101:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
Error: The following packages had errors: react-leaflet, react-router
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:118:8
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/test-runner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

**Comment by RyanCavanaugh** [comment]
@craigkovatch The linked PR should fix these - can you give it a fresh try?

**Comment by craigkovatch** [comment]
@RyanCavanaugh one remaining error:

```

Error in react-router
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-router/test/examples-from-react-router-website/CustomLink.tsx
ERROR: 27:71  expect  TypeScript@next compile error: 
Binding element 'match' implicitly has an 'any' type.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:101:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
Error: The following packages had errors: react-router
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:118:8
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/test-runner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by craigkovatch** [comment]
@RyanCavanaugh this is still blocking https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22582, do you know the right person to fix the remaining react-router issue?

**Comment by andy-ms** [comment]
That's Microsoft/TypeScript#21128
