### ISSUE TITLE
Problem defining virtual method for model with mongoose

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [DefinitelyTyped/DefinitelyTyped#27556]
- [x] I tried using the latest mongoose/mongoose.d.ts file in this repo and had problems.
- The authors of that type definition are @simonxca in #10084.

Basically this broke my use of mongoose. Not that I am sure I was using it correctly as I'm a bit of a novice in this TS/JS realm.

````js
export function install (schema: mongoose.Schema, opts?: any) {
  schema.virtual('password').set(function (password: string): void {
    // code..
  })
}
````
I started to compile a plugin that uses a virtual method and to my surprise
````
~/app/node_modules/mongoose/lib/schema.js:1473
    throw new Error('Virtual path "' + name + '"' +
          ^
Error: Virtual path "password" conflicts with a real path in the schema
    at Schema.virtual (~/app/node_modules/mongoose/lib/schema.js:1473:11)
    at Object.authenticable (~/app/lib/mongoose-devise/models/authenticable.ts:57:10)
    at devise (~/app/lib/mongoose-devise/mongoose-devise.ts:92:3)
    at Schema.plugin (~/app/node_modules/mongoose/lib/schema.js:1198:3)
    at Object.<anonymous> (~/app/src/usuarios/usuario.model.ts:27:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (~/app/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (~/app/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~/app/src/usuarios/usuario.routes.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
````
Thoughts?

**Comment by carvalhoviniciusluiz** [comment]
Forgiveness, the mistake was mine!
