### ISSUE TITLE
Building Angular Package Error :node_modules/@types/jasmine/index.d.ts(140,47): error TS1005: ';' expected.

### ISSUE THREAD

**Issue by Ibrahimov2501** [DefinitelyTyped/DefinitelyTyped#31889]
Am trying to convert some component to package and I followed below steps:
1- Creating new library using ng generate new library Test
2- Adding    "build:lib":"ng-packagr -p ./projects/test/ng-package.json" to package.json
3- Running command: npm run build:lib
After running last command I got this issue

BUILD ERROR
node_modules/@types/jasmine/index.d.ts(140,47): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(140,90): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(140,104): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(140,112): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(140,113): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(140,121): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(140,147): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(140,162): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(140,163): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(140,164): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(140,165): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(140,179): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(140,183): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(140,208): error TS1005: '{' expected.
node_modules/@types/jasmine/index.d.ts(140,217): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(140,222): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(140,227): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(140,228): error TS1109: Expression expected.
node_modules/@types/jasmine/index.d.ts(140,230): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(633,30): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(718,1): error TS1128: Declaration or statement expected.

Error: node_modules/@types/jasmine/index.d.ts(140,47): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(140,90): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(140,104): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(140,112): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(140,113): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(140,121): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(140,147): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(140,162): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(140,163): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(140,164): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(140,165): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(140,179): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(140,183): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(140,208): error TS1005: '{' expected.
node_modules/@types/jasmine/index.d.ts(140,217): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(140,222): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(140,227): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(140,228): error TS1109: Expression expected.
node_modules/@types/jasmine/index.d.ts(140,230): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(633,30): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(718,1): error TS1128: Declaration or statement expected.

    at Object.<anonymous> (C:\Users\Ibrahim\Desktop\AngularProject\Project\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at C:\Users\Ibrahim\Desktop\AngularProject\Project\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Ibrahim\Desktop\AngularProject\Project\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\Users\Ibrahim\Desktop\AngularProject\Project\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\Users\Ibrahim\Desktop\AngularProject\Project\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at C:\Users\Ibrahim\Desktop\AngularProject\Project\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

Please find devdependencies in my project:
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0",
    "@angular-devkit/build-ng-packagr": "~0.7.0",
    "@angular/cli": "~6.1.1",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^3.0.0",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }

**Comment by Ibrahimov2501** [comment]
I solved it by the below steps:
n package.json add

"typescript": "^2.9.2"

Run npm install.
