### ISSUE TITLE
jsdom breaks node tests

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#32444]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu @palmfjord @sandersn @RyanCavanaugh 

Seems the change in #30484 causes CI for node to fail with following message:
```
Error in jsdom
Error: Expected compilerOptions["baseUrl"] === "../"
    at Object.<anonymous> (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:4:58)
    at <anonymous>
```

see e.g. #32159

I don't know if this is a problem in jsdom itself or in dtslint.
Should we revert #30484?

**Comment by Flarna** [comment]
I would prefer if dtslint could be reverted/set to a version which worked. If I understand the history in #30484 correct there was some version with green CI.

Currently jsdom fails also standalone (at least local on my windows) but with a different error:
```
jsdom failing:
Error: c:/Workspaces/GithubForks/DefinitelyTyped/types/jsdom/ts3.1/index.d.ts:1:1
ERROR: 1:1  expect  Program source files differ between TypeScript versions. This may be a dtslint bug.
Expected to find a file 'c:/Workspaces/GithubForks/DefinitelyTyped/types/jsdom/ts3.1/index.d.ts' present in 3.3.0-dev.20190124, but did not find it in ts@3.0.

    at c:\Workspaces\GithubForks\DefinitelyTyped\node_modules\dtslint\bin\index.js:160:19
    at Generator.next (<anonymous>)
    at fulfilled (c:\Workspaces\GithubForks\DefinitelyTyped\node_modules\dtslint\bin\index.js:5:58)
    at <anonymous>
```

I created also an issue dtslint repo: https://github.com/Microsoft/dtslint/issues/186

**Comment by Flarna** [comment]
fix via https://github.com/Microsoft/dtslint/issues/186
