### ISSUE TITLE
[@types/stripe] Stripe.StripeError doesn't match exactly

### ISSUE THREAD

**Issue by JustinTRoss** [DefinitelyTyped/DefinitelyTyped#34559]
Tagging authors per issue creation template: @wjohnsto @CodeAnimal @sampsonjoliver @LinusU @brannon @kkamperschroer @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger

@types/stripe
Stripe Errors are incorrectly represented in the types. Below is an example of an error returned by stripe:

```json
{
      "type": "Error",
      "message": "Your card was declined.",
      "stack":
          Error: Your card was declined.
              at Constructor._Error (.../stripe/lib/Error.js:12:17)
              at Constructor (.../stripe/lib/utils.js:138:13)
              at new Constructor (.../stripe/lib/utils.js:138:13)
              at Function.StripeError.generate (.../stripe/lib/Error.js:55:12)
              at IncomingMessage.<anonymous> (.../stripe/lib/StripeResource.js:166:39)
              at IncomingMessage.emit (events.js:194:15)
              at IncomingMessage.EventEmitter.emit (domain.js:441:20)
              at endReadableNT (_stream_readable.js:1103:12)
              at process._tickCallback (internal/process/next_tick.js:63:19)
      "rawType": "card_error",
      "code": "card_declined",
      "raw": {
        "charge": "ch_13Npc4rDFeEcUd7Yt5Ez6rGhKZ",
        "code": "card_declined",
        "decline_code": "generic_decline",
        "doc_url": "https://stripe.com/docs/error-codes/card-declined",
        "message": "Your card was declined.",
        "type": "card_error",
        "headers": {
          "server": "nginx",
          "date": "Mon, 08 Apr 2019 16:47:17 GMT",
          "content-type": "application/json",
          "content-length": "269",
          "connection": "keep-alive",
          "access-control-allow-credentials": "true",
          "access-control-allow-methods": "GET, POST, HEAD, OPTIONS, DELETE",
          "access-control-allow-origin": "*",
          "access-control-expose-headers": "Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required",
          "access-control-max-age": "300",
          "cache-control": "no-cache, no-store",
          "request-id": "req_rko3VZ1kklhsuET",
          "stripe-version": "2019-02-11",
          "strict-transport-security": "max-age=31556926; includeSubDomains; preload"
        },
        "statusCode": 402,
        "requestId": "req_rko3VZ1kklhsuET"
      },
      "headers": {
        "server": "nginx",
        "date": "Mon, 08 Apr 2019 16:47:17 GMT",
        "content-type": "application/json",
        "content-length": "269",
        "connection": "keep-alive",
        "access-control-allow-credentials": "true",
        "access-control-allow-methods": "GET, POST, HEAD, OPTIONS, DELETE",
        "access-control-allow-origin": "*",
        "access-control-expose-headers": "Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required",
        "access-control-max-age": "300",
        "cache-control": "no-cache, no-store",
        "request-id": "req_rko3VZ1kklhsuET",
        "stripe-version": "2019-02-11",
        "strict-transport-security": "max-age=31556926; includeSubDomains; preload"
      },
      "requestId": "req_rko3VZ1kklhsuET",
      "statusCode": 402
    }
```

**Comment by SimonSchick** [comment]
Could you please highlight this mismatched section?

I can already tell that `readonly: number;` was incorrectly added, should be `readonly statusCode: number` but other than that?

**Comment by JustinTRoss** [comment]
```
    // IStripeError (extended by StripeError)
    type: string;
    message?: string;
    code?: string;
    param?: string;

    // StripeError
    readonly rawType: RawType;
    readonly code?: string;
    readonly raw: any;
    readonly headers: {
        [key: string]: string;
    };
    readonly requestId: string;
    readonly detail?: any;
    readonly: number;
    readonly params?: string;
    readonly type: string;

    // RawType
    type RawType = 'card_error' | 'invalid_request_error' | 'api_error' | 'idempotency_error';
```
raw should be typed rather than explicit any, as it is arguably the most important property in the bunch, being the error object expressed by docs. It should probably be something like:

```
charge?: string,
code: RawCode, // enum
decline_code?: DeclineCode, // enum
doc_url: string,
message?: string,
type: RawType,
headers: {
    ...
},
statusCode: number,
requestId: string
```

IStripeError.type and IStripeError.code should likely be enums.

RawType should be enum and, I haven't confirmed yet, but I expect it can be more types that this according to docs. Something like this:

```
enum RawType {
  API_CONNECTION_ERROR = 'api_connection_error',
  API_ERROR = 'api_error',
  AUTHENTICATION_ERROR = 'authentication_error',
  CARD_ERROR = 'card_error',
  IDEMPOTENCY_ERROR = 'idempotency_error',
  INVALID_REQUEST_ERROR = 'invalid_request_error',
  RATE_LIMIT_ERROR = 'rate_limit_error',
  VALIDATION_ERROR = 'validation_error',
}
```

I'll try to make time to update it at some point this week.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
