### ISSUE TITLE
stderr maxBuffer length exceeded when running tests

### ISSUE THREAD

**Issue by Stadly** [DefinitelyTyped/DefinitelyTyped#35740]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DefinitelyTyped

If you do not mention the authors the issue will be ignored.

When I run `npm run test`, I get the following output:

```
> node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed

Clean data
Clean logs
Clean output
^[{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at Socket.onChildStderr (child_process.js:382:14)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:272:13)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:150:17) cmd: 'git diff --name-only' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! definitely-typed@0.0.3 test: `node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the definitely-typed@0.0.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-25T13_38_42_644Z-debug.log
```

It seems that `maxBuffer` should be increased when the tests run. Or am I doing something wrong?

**Comment by lex-rmondal** [comment]
Anyone knows how to fix this? I'm also getting this same issue while running test on our app. It uses clean-script tasks to run the test on angular 10 app.
