### ISSUE TITLE
Commit a513c860 - Added type definitions for neverbounce (#36238) - makes `npm test` fail

### ISSUE THREAD

**Issue by hlovdal** [DefinitelyTyped/DefinitelyTyped#36352]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @georgenov

Commit a513c860 from #36238 breaks `npm test`:

```shell
=== ERRORS ===



Error in neverbounce
Error: C:/github/forks/DefinitelyTyped/types/neverbounce/index.d.ts:2:1
ERROR: 2:1  npm-naming  At least one of the project urls listed in the header, ["https://github.com/NeverBounce/NeverBounceApi-NodeJS"], must match the homepage listed by npm, 'https://neverbounce.com'.
If your d.ts file is not for the npm package with URL https://neverbounce.com,
change the name by adding -browser to the end and change the first line
of the Definitely Typed header to

    // Type definitions for non-npm package neverbounce-browser
 See: https://github.com/Microsoft/dtslint/blob/master/docs/npm-naming.md

    at C:\github\forks\DefinitelyTyped\node_modules\dtslint\bin\index.js:189:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\github\forks\DefinitelyTyped\node_modules\dtslint\bin\index.js:5:58)
    at <anonymous>
Error: The following packages had errors: neverbounce
    at doRunTests (C:\github\forks\DefinitelyTyped\node_modules\types-publisher\src\tester\test-runner.ts:235:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by hlovdal** [comment]
Commit a513c860 was one of (only) two commits that failed when I ran git bisect, however when trying to reproduce minimally now

```shell
mkdir /tmp/dttest2
cd /tmp/dttest2
git clone https://github.com/DefinitelyTyped/DefinitelyTyped
cd DefinitelyTyped/
git reset --hard a513c860
npm install
npm test
```

it does not fail, so it seems to be a false error report on my part, sorry.
