### ISSUE TITLE
Commit 8deb2a8 - Add types for commander-remaining-args (#36148) - makes `npm test` fail

### ISSUE THREAD

**Issue by hlovdal** [DefinitelyTyped/DefinitelyTyped#36353]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ffflorian

Commit 8deb2a8 from #36148 breaks `npm test`:

```shell
Error: In package.json: Dependency commander not in whitelist.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
If this is an external library that provides typings,  please make a pull request to types-publisher adding it to `dependenciesWhitelist.txt`.
    at checkPackageJsonDependencies (C:\github\forks\DefinitelyTyped\node_modules\types-publisher\src\lib\definition-parser.ts:204:19)
    at combineDataForAllTypesVersions (C:\github\forks\DefinitelyTyped\node_modules\types-publisher\src\lib\definition-parser.ts:99:37)
    at <anonymous>
Error: Parsing failed.
    at fail (C:\github\forks\DefinitelyTyped\node_modules\types-publisher\src\util\util.ts:313:20)
    at ChildProcess.child.on (C:\github\forks\DefinitelyTyped\node_modules\types-publisher\src\util\util.ts:301:21)
    at emitNone (events.js:106:13)
    at ChildProcess.emit (events.js:208:7)
    at finish (internal/child_process.js:747:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! Test failed.  See above for more details.
```

**Comment by ffflorian** [comment]
@hlovdal
As you can see in one of the latest [Travis runs on master](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/549021380), `npm test` doesn't fail.

Did you run `npm install` before testing?

**Comment by hlovdal** [comment]
Hm. Commit 8deb2a8  was one of (only) two commits that failed when I ran `git bisect`, however when trying to reproduce minimally

```shell
cd /tmp
mkdir dttest
cd dttest
git clone https://github.com/DefinitelyTyped/DefinitelyTyped
cd DefinitelyTyped
git checkout master
git reset --hard 8deb2a8
npm install
npm test
```

it does not fail, so it seems to be a false error report on my part, sorry.
