### ISSUE TITLE
Document how to run all tests

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#37719]
The documentation does not provide instructions for how to run all tests. This is necessary when making changes to types in a library which is used by lots of other libraries, e.g. Express.

I tried running `npm test` but I get errors:

/cc @sandersn 

``` sh-session
$ npm test

> definitely-typed@0.0.3 test /Users/oliverash/Development/DefinitelyTyped
> node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed

Clean data
Clean logs
Clean output
Using local Definitely Typed at /Users/oliverash/Development/DefinitelyTyped.
Parsing definitions...
Found 6071 packages.
Parsing in parallel...
Error: In package.json: Dependency @vue/test-utils not in whitelist.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
If this is an external library that provides typings,  please make a pull request to types-publisher adding it to `dependenciesWhitelist.txt`.
    at checkPackageJsonDependencies (/Users/oliverash/Development/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:204:19)
    at combineDataForAllTypesVersions (/Users/oliverash/Development/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:99:37)
    at <anonymous>
Error: Parsing failed.
    at fail (/Users/oliverash/Development/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:313:20)
    at ChildProcess.child.on (/Users/oliverash/Development/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:301:21)
    at emitNone (events.js:106:13)
    at ChildProcess.emit (events.js:208:7)
    at finish (internal/child_process.js:747:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! Test failed.  See above for more details.
```

**Comment by OliverJAsh** [comment]
Turns out I had an old version of `types-publisher` installed. Running `yarn` didn't fix it, I had to wipe my Git project clean and install from scratch.

``` bash
git clean -xfd && npm install
```

**Comment by PikachuEXE** [comment]
@OliverJAsh 
Running `yarn` didn't fix it since it's locked already
You need to run `yarn upgrade types-publisher` to get latest production version from Github
