### ISSUE TITLE
CI/Travis/npm install failing

### ISSUE THREAD

**Issue by staeke** [DefinitelyTyped/DefinitelyTyped#38512]
@sandersn 

https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/587697682#L301

```
Error: Error: Command failed: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links --no-save
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /home/travis/.npm/_locks/staging-6e176fca3631bcf6.lock
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/home/travis/.npm/_locks/staging-6e176fca3631bcf6.lock'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-09-20T23_17_41_333Z-debug.log
    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /home/travis/.npm/_locks/staging-6e176fca3631bcf6.lock
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/home/travis/.npm/_locks/staging-6e176fca3631bcf6.lock'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-09-20T23_17_41_333Z-debug.log
    at Object.execAndThrowErrors (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:166:15)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! definitely-typed@0.0.3 test: `node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the definitely-typed@0.0.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-09-20T23_17_41_624Z-debug.log
The command "npm run test" exited with 1.
0.01s$ if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then npm run update-codeowners || travis_terminate 1; fi
The command "if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then npm run update-codeowners || travis_terminate 1; fi" exited with 0.
cache.2
store build cache
Done. Your build exited with 1.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
