### ISSUE TITLE
[styled-components] No overload matches this call for attrs components

### ISSUE THREAD

**Issue by kirill-konshin** [DefinitelyTyped/DefinitelyTyped#42691]
```ts
export const Badge = styled.span.attrs<{danger?: boolean}>(props => ({
    className: `badge badge-warning ${props.danger && 'badge-danger'}`,
}))`
    ${marginLeft};
`;
```

Results in a following error at usage point during compilation:

```
No overload matches this call.
  Overload 1 of 2, '(props: Pick<Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, "style" | "title" | ... 252 more ... | "onTransitionEndCapture"> & { ...; }, "ref" | ... 254 more ... | "onTransitionEndCapture"> & Partial<...>, "ref" | ... 254 more ... | "onTransitionEndCapture"> & { ...; } & { ...; }): ReactElement<...>', gave the following error.
```

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @surgeboris @sandersn @Jessidhia @smockle @Igorbek @Igmat @Lavoaster @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2

**Comment by jeanbispo** [comment]
I'm having a similar problem

![Captura de tela de 2020-02-29 19-27-54](https://user-images.githubusercontent.com/17678567/75615989-a64be580-5b29-11ea-9580-260f6c6e1d6f.png)

**Comment by archangel-irk** [comment]
I have the same problem with `styled.input` and `size` attribute. I want to use this attribute in my component but since SC passes this attr to html input the typings are incorrect for me.

Is the solution to avoid using well known html attributes like `size`?

**Comment by hankchiutw** [comment]
I got the `No overload matches this call` error in a similar scenario and have a workaround.

**What I encountered**
I defined a styled component like this:
```
interface WrapperProps {
  color: MyColorType;
}
const Wrapper = styled.input.attrs((props: WrapperProps) => {
  return {
    style: {
      background: ``,
    },
  };
})``;
```
and use it like the following:
```
<Wrapper as="input" color={color}></Wrapper>
```
Thus I got the error `No overload matches this call` for `color={color}`.

**Workaround to avoid the error**
```
const Wrapper = styled.input.attrs((props: WrapperProps) => {
  return {
    color: props.color,  // <-- add this line
    style: {
      background: ``,
    },
  };
})``;
```
Actually, not only `props.color`, setting any value to `color` seems also work.

**Comment by jtanadi** [comment]
I was running into the same problem, but was able to solve it based on this [SO answer](https://stackoverflow.com/a/52405602/9569550).

So based on @kirill-konshin's code, something like this worked for me:
```js
type PropType = {
  danger?: boolean
}

export const Badge = styled.span.attrs((props: PropType) => ({
    className: `badge badge-warning ${props.danger && 'badge-danger'}`,
}))<PropType>`
    ${marginLeft};
`;
```

**Comment by plonko** [comment]
I get this error in VS Code and I'm not using Typescript :/

**Comment by lucasReghiniM** [comment]
> OR this:
> 
> ```
> type OtherDataWrapperType = {
>     fullWidth?: boolean
> }
> ```
> 
> ```
> export const OtherDataWrapper = s.div<OtherDataWrapperType>`
>     display: flex;
>     justify-content: ${p => p.fullWidth ? 'center' : 'space-between'} ;
> ```
> 
> ```
>         <OtherDataWrapper fullWidth={true}>
>             <Merchant>{merchant}</Merchant>
>             <div>{amount.value} {amount.currency}</div>
>         </OtherDataWrapper>
> ```

I did this, but the problem continues.
I tried with interface and happens he same thing.

obs: That error just appers in xml-React (index) file, the styles file still normal.

**Comment by mtrabelsi** [comment]
@lucas can you share some code?

**Comment by lucasReghiniM** [comment]
> @lucas can you share some code?
That os the error now

```
Watching source, compiling to dist:
Error: Could not resolve './styles' from src/UI/Button/index.tsx

    at error (/home/****/Documentos/workbench/***/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/home/***/Documentos/workbench/***/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (/home/***/Documentos/workbench/***/node_modules/rollup/dist/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/***/Documentos/workbench/***/node_modules/rollup/dist/shared/node-entry.js:38:28)

Error: Could not resolve './styles' from src/UI/Button/index.tsx

    at error (/home/***/Documentos/workbench/***/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/home/***/Documentos/workbench/***/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (/home/***/Documentos/workbench/***/node_modules/rollup/dist/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/***/Documentos/workbench/***/node_modules/rollup/dist/shared/node-entry.js:38:28)
```
The Button component

index.tsx:

```
import React from 'react';

import { Container, GeralProps } from './styles';



const Button: React.FC<GeralProps> = ({children, ...rest}) => {
	return <Container {...rest}>{children}</Container>;
}

export default Button;
```

styles.ts

```
import styled from 'styled-components';

export type GeralProps = {
    width: string;
    maxWidth: string;
    minWidth: string;

    height: string;
    maxHeight: string;
    minHeight: string;

    margin: string;
    padding: string;

    overflow: string;
    overflowX: string;
    overflowY: string;
    zIndex: string;

    position: string;
    top: string;
    bottom: string;
    left: string;
    right: string;

    display: string;
    justify: string;
    align: string;
    talign: string;
    fdirect: string;

    background : string;
    shadow: string;
    opacity: string;

    border: string;
    borderTop: string;
    borderBottom: string;
    borderLeft: string;
    borderRight: string;
    radius: string;

    font: string;
    color: string;
    bgcolor: string

    transition: string;
    transform: string;

    custom: string;

    mobile: string;
    tablet: string;

    hover: string;
    active: string;

    webkitScrollbar : string;
    webkitScrollbarThumb: string;
    webkitScrollbarTrack: string;
}


export const Container = styled.button<GeralProps>`
    //Padrao
    width: ${p => p.width || 'auto'};
    max-width: ${(p) => p.maxWidth };
    min-width: ${(p) => p.minWidth };

    height: ${p => p.height || 'auto'};
    max-height: ${(p) => p.maxHeight };
    min-height: ${(p) => p.minHeight };
  
    margin: ${p => p.margin || '0'};
    padding: ${p => p.padding || '4px 16px'};

    overflow: ${(p) => p.overflow};
    overflow-x: ${(p) => p.overflowX};
    overflow-y: ${(p) => p.overflowY};
    z-index: ${p => p.zIndex};

    position: ${(p) => p.position};
    top: ${(p) => p.top};
    bottom: ${(p) => p.bottom};
    left: ${(p) => p.left};
    right: ${(p) => p.right};

    display: ${p => p.display || 'flex'};
    justify-content: ${p => p.justify || 'center'};
    align-items: ${p => p.align || 'center'};
    text-align: ${(p) => p.talign};
    flex-direction:  ${(p) => p.fdirect};

    background: ${p => p.background || 'var(--green)'};
    box-shadow: ${(p) => p.shadow || '0'};
    opacity: ${(p) => p.opacity };  

    border: ${(p) => p.border || 'none'};
    border-top: ${(p) => p.borderTop || 'none'};
    border-bottom: ${(p) => p.borderBottom || 'none'};
    border-left: ${(p) => p.borderLeft || 'none'};
    border-right: ${(p) => p.borderRight || 'none'};
    border-radius: ${p => p.radius || '0'};

    font: ${p => p.font || 'bold 14px/18px Nunito'};  
    color: ${p => p.color || '#FFFFFF'};  
    background-color:${p => p.bgcolor };	

    transition: ${(p) => p.transition || 'all ease 0.3s'};
    transform: ${(p) => p.transform};

    ${p => p.custom};
  
    //Resizes
    @media(max-width: 425px){
        ${p => p.mobile};
    }
    @media(max-width: 768px){
        ${p => p.tablet};
    }
  
  //Efeitos
    &:hover {
        ${p => p.hover};
    }

    &:active {
        ${p => p.active};
        transform: scale(0.9,0.9);
    }
  
	&::-webkit-scrollbar {    
        ${p => p.webkitScrollbar || 'display: none;'};
	}

	&::-webkit-scrollbar-thumb {
        ${p => p.webkitScrollbarThumb};
	}

    &::-webkit-scrollbar-track {
        ${p => p.webkitScrollbarTrack};
    }
`;
```

**Comment by Arukiap** [comment]
Hi everyone! I am reporting an issue I found that I believe is in the scope of this one:

In my project, I have a library of React components that can represent different html semantic elements based on the value of the `renderAs` prop you pass. 

```ts
type Props = {
  readonly renderAs: 'link';
  (...)
} | {
  readonly renderAs: 'button';
  (...)
} | {
  readonly renderAs: 'div';
  (...)
};

type Overloads = {
  (props: Extract<Props, { renderAs: 'link' }> & React.RefAttributes<HTMLAnchorElement>): N<React.ReactElement>;
  (props: Extract<Props, { renderAs: 'button' }> & React.RefAttributes<HTMLButtonElement>): N<React.ReactElement>;
  (props: Extract<Props, { renderAs: 'div' }> & React.RefAttributes<HTMLDivElement>): N<React.ReactElement>;
};

export const Button: Overloads = React.forwardRef<HTMLAnchorElement | HTMLButtonElement | HTMLDivElement, Props>((props, ref) => {

(...)
```

The issue is that when I import this Button in another file, and I try to style it like:

```ts
const StyledButton = styled(Button)`
   (styles here)
`;
```

I run into the following typing issue:

![Screenshot 2021-05-27 at 09 24 42](https://user-images.githubusercontent.com/33361409/119783299-60690300-becd-11eb-97d0-64f0785d8a9b.png)

It seems that TS is not able to match the current value of `renderAs` to the right overload.

**Importing the type and passing it to the `styled` function fixes this issue, like @mtrabelsi explained.**

Nevertheless, I am building a components library to be used by other developers. This would mean that they would have to be aware of this intricacy whenever they want to style one of the components that I provide. So my question is: 

Is there a way of fixing this issue such that you don't have to import the types from the file your component is defined in?

**Comment by manudevcode** [comment]
> I was running into the same problem, but was able to solve it based on this [SO answer](https://stackoverflow.com/a/52405602/9569550).
> 
> So based on @kirill-konshin's code, something like this worked for me:
> 
> ```js
> type PropType = {
>   danger?: boolean
> }
> 
> export const Badge = styled.span.attrs((props: PropType) => ({
>     className: `badge badge-warning ${props.danger && 'badge-danger'}`,
> }))<PropType>`
>     ${marginLeft};
> `;
> ```

That works perfectly

**Comment by CaaioSB** [comment]
I found a solution, but idk if are good.

Do that:

`const YourStyledComponent = styled.div<Partial<YourInterface>>`

"`Partial<YourInterface>`" transform all props in `YourInterface` optional, but thats work only in 2.1+ Typescript
