### ISSUE TITLE
Issue with running test command

### ISSUE THREAD

**Issue by Eddie-CooRo** [DefinitelyTyped/DefinitelyTyped#44558]
I get this error when I try to run test on the types I newly added.

```
Error: In package.json: Dependency glaze not in whitelist.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
For namespaced dependencies you then have to add a `paths` mapping from `@namespace/library` to `namespace__library` in `tsconfig.json`.
If this is an external library that provides typings,  please make a pull request to types-publisher adding it to `dependenciesWhitelist.txt`.
    at checkPackageJsonDependencies (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:187:19)
    at combineDataForAllTypesVersions (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:104:37)
    at Object.getTypingInfo (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:27:82)
    at /home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser-worker.js:17:50
    at Object.logUncaughtErrors (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/types-publisher/bin/util/util.js:78:38)
    at process.<anonymous> (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser-worker.js:15:16)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Error: Parsing failed.
    at fail (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/types-publisher/bin/util/util.js:272:20)
    at ChildProcess.<anonymous> (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/types-publisher/bin/util/util.js:261:21)
    at ChildProcess.emit (events.js:210:5)
    at finish (internal/child_process.js:861:14)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

(I was able to find the glaze dependency inside of the babel-plugin-glaze package folder)

cc @kripod

**Comment by peterblazejewicz** [comment]
@Eddie-CooRo 
This should help:
```bash
git fetch upstream
git pull upstream master
git clean -xfd
npm install
```
This is one of the largest monorepos on the GitHub, the problem like one above arises from outdated dependencies and build artefacts. So it's best to always restart clean when working on one's own changes.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
