### ISSUE TITLE
Issue in lint command

### ISSUE THREAD

**Issue by Eddie-CooRo** [DefinitelyTyped/DefinitelyTyped#44557]
I get this error when I try to lint the types I newly added.
```
$ dtslint types generate-password
Installing to /home/eddie/.dts/typescript-installs/3.0...
Installed!

Installing to /home/eddie/.dts/typescript-installs/3.1...
Installed!

Installing to /home/eddie/.dts/typescript-installs/3.2...
Installed!

Installing to /home/eddie/.dts/typescript-installs/3.3...
Installed!

Installing to /home/eddie/.dts/typescript-installs/3.4...
Installed!

Installing to /home/eddie/.dts/typescript-installs/3.5...

Installed!

Installing to /home/eddie/.dts/typescript-installs/3.6...
Installed!

Installing to /home/eddie/.dts/typescript-installs/3.7...
Installed!

Installing to /home/eddie/.dts/typescript-installs/3.8...
Installed!

Installing to /home/eddie/.dts/typescript-installs/3.9...

Installed!

Error: Cannot find module '/home/eddie/.dts/typescript-installs/2.8/node_modules/typescript'
Require stack:
- /home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/dtslint/bin/lint.js
- /home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/dtslint/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at testDependencies (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/dtslint/bin/lint.js:64:16)
    at Object.<anonymous> (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/dtslint/bin/lint.js:26:28)
    at Generator.next (<anonymous>)
    at /home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/dtslint/bin/lint.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/eddie/Desktop/opensource/DefinitelyTyped/node_modules/dtslint/bin/lint.js:4:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I don't know why it's trying to access the 2.8 folder while it only started installing from the 3.0.

---

Removing ~/.dts/typescript-installs/2.8 and re-running the command fixed the issue.

**Comment by peterblazejewicz** [comment]
@Eddie-CooRo probably same problem as in #44558

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
