### ISSUE TITLE
[@types/node] Failed tests when run locally

### ISSUE THREAD

**Issue by Semigradsky** [DefinitelyTyped/DefinitelyTyped#48257]
@sandersn @rbuckton @ExE-Boss  

Currently I have these errors when run `npm run test node`:

```
> definitely-typed@0.0.3 test /home/dmitry/H/DefinitelyTyped
> dtslint types "node"

testing from 3.1 to 3.4 in /home/dmitry/H/DefinitelyTyped/types/node/ts3.4
Error: Errors in typescript@3.1 for external dependencies:
../fs.d.ts(2139,52): error TS2304: Cannot find name 'bigint'.
../fs.d.ts(2143,18): error TS2304: Cannot find name 'bigint'.
../fs.d.ts(2144,18): error TS2304: Cannot find name 'bigint'.
../fs.d.ts(2145,18): error TS2304: Cannot find name 'bigint'.
../fs.d.ts(2146,22): error TS2304: Cannot find name 'bigint'.
../globals.d.ts(259,28): error TS2304: Cannot find name 'bigint'.
../globals.d.ts(260,28): error TS2304: Cannot find name 'bigint'.
../globals.d.ts(261,29): error TS2304: Cannot find name 'bigint'.
../globals.d.ts(262,29): error TS2304: Cannot find name 'bigint'.
../globals.d.ts(267,39): error TS2304: Cannot find name 'bigint'.
../globals.d.ts(268,39): error TS2304: Cannot find name 'bigint'.
../globals.d.ts(269,38): error TS2304: Cannot find name 'bigint'.
../globals.d.ts(270,38): error TS2304: Cannot find name 'bigint'.
../process.d.ts(87,27): error TS2304: Cannot find name 'bigint'.
../util.d.ts(128,56): error TS2304: Cannot find name 'BigInt64Array'.
../util.d.ts(129,57): error TS2304: Cannot find name 'BigUint64Array'.

    at /home/dmitry/H/DefinitelyTyped/node_modules/dtslint/bin/index.js:206:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/dmitry/H/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

Looks like it related to this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47645

**Comment by sandersn** [comment]
Looks like you're working with an old version of DT or its dependencies. Here's the output for me:

```
$ npm run test node

> definitely-typed@0.0.3 test /home/nathansa/DefinitelyTyped
> dtslint types "node"

testing from 3.2 to 3.4 in /home/nathansa/DefinitelyTyped/types/node/ts3.4
testing from 3.5 to 3.6 in /home/nathansa/DefinitelyTyped/types/node/ts3.6
testing from 3.7 to 4.1 in /home/nathansa/DefinitelyTyped/types/node
```

It's not even testing 3.1 anymore.

**Comment by Semigradsky** [comment]
My fault! Looks like it was yarn cache issue or smth like this. The issue gone when I removed `node_modules` and installed dependencies via npm. Thank you!
