### ISSUE TITLE
All CI workflow jobs failing as of 2021-03-17 08:30 UTC+0

### ISSUE THREAD

**Issue by pastelmind** [DefinitelyTyped/DefinitelyTyped#51835]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

----

All PRs have been failing the [**CI** workflow](https://github.com/DefinitelyTyped/DefinitelyTyped/actions/workflows/CI.yml) since approximately 2021-03-17 08:30 UTC+0. [This run](https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/660420438) is the first one that failed.

Most failed runs have logs that look like this:
<details>
<summary>Log taken from <a href="https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51832/checks?check_run_id=2135638908">run ID 2135638908</a></summary>

```
Using local DefinitelyTyped at .
Parsing definitions...
Found 7575 packages.
Parsing in 2 child process(es)...

<--- Last few GCs --->

[1645:0x47e5100]     7509 ms: Scavenge 1185.6 (1218.8) -> 1185.6 (1218.8) MB, 81.4 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[1645:0x47e5100]     9817 ms: Mark-sweep 1759.4 (1792.6) -> 1716.3 (1754.3) MB, 569.5 / 0.0 ms  (+ 64.5 ms in 8 steps since start of marking, biggest step 15.6 ms, walltime since start of marking 6469 ms) (average mu = 0.933, current mu = 0.933) allocatio

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x140a7f9]
Security context: 0x348acb5808d1 <JSObject>
    1: push [0x348acb59a281](this=0x07693661bf59 <JSArray[112813858]>,0x041faad80731 <String[#0]: >)
    2: parseJSDocLink(aka parseJSDocLink) [0x1b1eaffc10e1] [/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/typescript/lib/typescript.js:~35499] [pc=0x34ce28c6ebba](this=0x041faad804b1 <undefined>,28936)
    3: parseTagComments(aka parseTagComments)...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0xa18150 node::Abort() [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
 2: 0xa1855c node::OnFatalError(char const*, char const*) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
 3: 0xb9705e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
 4: 0xb973d9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
 5: 0xd54655  [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
 6: 0xd2c640 v8::internal::Factory::NewUninitializedFixedArray(int, v8::internal::AllocationType) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
 7: 0xe9bb31  [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
 8: 0xeb54d2  [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
 9: 0xeb574b  [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
10: 0xf03302 v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
11: 0xf4f88a v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
12: 0xf505c7 v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
13: 0x1084c54 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
14: 0x1085e1a v8::internal::Runtime_SetKeyedProperty(int, unsigned long*, v8::internal::Isolate*) [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
15: 0x140a7f9  [/opt/hostedtoolcache/node/12.21.0/x64/bin/node]
Error: Parsing failed.
    at fail (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/utils/dist/process.js:80:20)
    at ChildProcess.<anonymous> (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/utils/dist/process.js:67:21)
    at ChildProcess.emit (events.js:314:20)
    at finish (internal/child_process.js:862:14)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! definitely-typed@0.0.3 test-all: `node node_modules/@definitelytyped/dtslint-runner/dist/index.js --path .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the definitely-typed@0.0.3 test-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
</details>

From a glance, it looks like the VM is running out of memory.

**Comment by weswigham** [comment]
FYI, we've temporarily fixed this by pinning the nightly TS we test against to a prior version while we track down the exact circumstances causing the OOM. Tests should be runnable across DT again for now, though.
