### ISSUE TITLE
koa-pino-logger tests failing

### ISSUE THREAD

**Issue by thewilkybarkid** [DefinitelyTyped/DefinitelyTyped#58234]
#58184 failed on an unchanged module (`koa-pino-logger`). I've tried running `npm test koa-pino-logger` on `master` and it still fails, even after following the suggestions:

```
[$] ➜ npm test koa-pino-logger

> definitely-typed@0.0.3 test
> dtslint types "koa-pino-logger"

Error:
A module look-up failed, this often occurs when you need to run `npm install` on a dependent module before you can lint.

Before you debug, first try running:

   npm install --prefix [...]/DefinitelyTyped/DefinitelyTyped/types/pino-http

Then re-run. Full error logs are below.

Errors in typescript@4.6 for external dependencies:
../pino-http/index.d.ts(11,65): error TS2307: Cannot find module 'pino' or its corresponding type declarations.

    at testTypesVersion ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:189:15)
    at async runTests ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:165:13)
    at async main ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:77:9)
[$] ➜  npm install --prefix [...]/DefinitelyTyped/DefinitelyTyped/types/pino-http

added 6 packages, and audited 7 packages in 2s

found 0 vulnerabilities
[$] ➜ npm test koa-pino-logger

> definitely-typed@0.0.3 test
> dtslint types "koa-pino-logger"

Error:
A module look-up failed, this often occurs when you need to run `npm install` on a dependent module before you can lint.

Before you debug, first try running:

   npm install --prefix [...]/DefinitelyTyped/DefinitelyTyped/types/pino-pretty

Then re-run. Full error logs are below.

Errors in typescript@4.6 for external dependencies:
../pino-pretty/index.d.ts(8,31): error TS2307: Cannot find module 'pino' or its corresponding type declarations.

    at testTypesVersion ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:189:15)
    at async runTests ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:165:13)
    at async main ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:77:9)
[$] ➜ npm install --prefix [...]/DefinitelyTyped/DefinitelyTyped/types/pino-pretty

added 6 packages, and audited 7 packages in 517ms

found 0 vulnerabilities
[$] ➜ npm test koa-pino-logger

> definitely-typed@0.0.3 test
> dtslint types "koa-pino-logger"

Error: [...]/DefinitelyTyped/DefinitelyTyped/types/koa-pino-logger/index.d.ts:9:43
ERROR: 9:43  expect  TypeScript@4.6 compile error:
Cannot find module 'pino' or its corresponding type declarations.

    at testTypesVersion ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:189:15)
    at async runTests ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:165:13)
    at async main ([...]/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/bin/src/index.js:77:9)
```

I noticed the types for `pino` was removed recently (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57023), and `koa-pino-logger` does have a dependency on the old types https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ae92a0038d332a031736db00fb953aca41928ad7/types/koa-pino-logger/package.json#L3-L5

I assume #58184 caused the `koa-pino-logger` tests to run as it changed another dependent module (`koa`).

Also, `TypeScript@4.6` isn't released yet either.

I'm not sure where to look now to find out what's missing/wrong.

**Comment by damusix** [comment]
Having the same issue except it's telling me `Error: Errors in typescript@3.8 for external dependencies:`, however, my typescript version in `node_modules` is `4.6-dev`

**Comment by thewilkybarkid** [comment]
`TypeScript@4.6` has been released; I now see:

```
ERROR: 9:43  expect  TypeScript@4.7 compile error: 
Cannot find module 'pino' or its corresponding type declarations.
```

**Comment by thewilkybarkid** [comment]
From @BendingBender https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58184#issuecomment-1086886451:

> ~@thewilkybarkid Regarding the breakage in `koa-pino-logger`, I think you can fix it by adding a `package.json` there with the contents:~
> 
> ```json
> {
>     "private": true,
>     "dependencies": {
>         "@types/pino": "^6"
>     }
> }
> ```
> 
> ~`@types/pino` is already whitelisted in https://github.com/microsoft/DefinitelyTyped-tools.~
> 
> Just noticed that there are already all necessary `package.json`s in the transitive packages. Just push a new commit/force push to your branch, the CI run should pass.

No luck, unfortunately. Still failing on `master` too.
