### ISSUE TITLE
[DT Infra] Deleted accounts job still failing

### ISSUE THREAD

**Issue by MysteryBlokHed** [DefinitelyTyped/DefinitelyTyped#60978]
An issue that was stopping some CI jobs from working was fixed in #60664, but the job to remove deleted accounts (`ghostbuster.yml`) is still failing: <https://github.com/DefinitelyTyped/DefinitelyTyped/actions/workflows/ghostbuster.yml?query=is%3Afailure>

The issue seems to happen when trying to write to files. But I'm not entirely sure why it doesn't work, since reading files works fine.

<details open>
<summary>Logs for failing job</summary>

```text
Run node ./scripts/ghostbuster.js
Reading headers...
Checking for deleted accounts...
Found one or more deleted accounts in file:///home/runner/work/DefinitelyTyped/DefinitelyTyped/types/animejs/index.d.ts. Patching...
Error: ENOENT: no such file or directory, open 'file:///home/runner/work/DefinitelyTyped/DefinitelyTyped/types/animejs/index.d.ts'
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2170:35)
    at bust (file:///home/runner/work/DefinitelyTyped/DefinitelyTyped/scripts/ghostbuster.js:41:13)
    at file:///home/runner/work/DefinitelyTyped/DefinitelyTyped/scripts/ghostbuster.js:154:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'file:///home/runner/work/DefinitelyTyped/DefinitelyTyped/types/animejs/index.d.ts'
}
```
</details>

**Comment by MysteryBlokHed** [comment]
It looks like this got fixed around 3 months ago: <https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/2659541488>
