### ISSUE TITLE
test-all failed with exit code 1

### ISSUE THREAD

**Issue by jbovone** [DefinitelyTyped/DefinitelyTyped#61192]
Hi!

The stack trace:

```
[julian@fedora DefinitelyTyped]$ yarn test-all
yarn run v1.22.10
$ node --require source-map-support/register node_modules/@definitelytyped/dtslint-runner/ --path .
dtslint-runner@0.0.115
Using local DefinitelyTyped at .
Parsing definitions...
Found 8162 packages.
Parsing in 4 child process(es)...
Error: .eslintrc.json: filesystem doesn't support paths of the form './x'.
    at validatePath (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/utils/src/fs.ts:196:11)
    at DiskFS.getPath (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/utils/src/fs.ts:158:5)
    at DiskFS.isDirectory (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/utils/src/fs.ts:169:26)
    at checkAllUsedRecur (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:709:12)
    at checkAllFilesUsed (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:696:3)
    at getTypingDataForSingleTypesVersion (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:332:3)
    at combineDataForAllTypesVersions (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:210:23)
    at getTypingInfo (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:71:15)
    at /home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser-worker.ts:17:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: disconnect with 2010 outputs left
    at ChildProcess.<anonymous> (/home/julian/Documents/Projects/DefinitelyTyped/node_modules/@definitelytyped/utils/src/process.ts:77:16)
    at ChildProcess.emit (node:events:520:28)
    at finish (node:internal/child_process:922:14)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I tried erasing node_modules and reinstalling. No luck there. The local is up to date. 
Thanks!

**Comment by jbovone** [comment]
>  "version": "0.0.115"
ups, yes! that was the stuff!
Thanks!
 
So, we need erase node_modules, and erase the lock file.

**Comment by jablko** [comment]
Ah yes, that would would do it. Glad it's working now! :+1:
