### ISSUE TITLE
Files form my other pull request ? 

### ISSUE THREAD

**Issue by Soldy** [DefinitelyTyped/DefinitelyTyped#61373]
I have an error message about a file what is not in my pull request.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61370
 
 I have an error message : 
```
Error: Expected file 'levelrunnerrc-tests.ts' to be named 'assertrc-tests.ts' or to be inside a './types/assertrc/test/' directory
    at checkFilesFromTsConfig (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:493:15)
    at getTypingDataForSingleTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:309:3)
    at combineDataForAllTypesVersions (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:210:23)
    at getTypingInfo (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser.ts:71:15)
    at /home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/definitions-parser/src/lib/definition-parser-worker.ts:17:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: disconnect with 3778 outputs left
    at ChildProcess.<anonymous> (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/utils/src/process.ts:77:16)
    at ChildProcess.emit (events.js:314:20)
    at finish (internal/child_process.js:862:14)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

But the  ```levelrunnerrc-tests.ts``` not in my pull request. The ```types/assertrc/levelrunnerrc-tests.ts``` not exist at all.

**Comment by Soldy** [comment]
I put a new pull request with new branch still same ....

**Comment by Soldy** [comment]
Visual Studio Issues. Files are not updated in the cloud after save.
