### ISSUE TITLE
New clone fails to run tests with missing `no-import-default-of-export-equals`

### ISSUE THREAD

**Issue by connor4312** [DefinitelyTyped/DefinitelyTyped#64910]
1. Clone DT
2. Run `npm i --legacy-peer-deps` as instructed
3. Run `npm test node`, or any other package
4. See the error 🐛 

Full output here. I updated to the latest Node 19.x, but this happened on my previous 16.x as well:

```
PS C:\Users\conno\Github\DefinitelyTyped> node --version
v19.8.1
PS C:\Users\conno\Github\DefinitelyTyped> npm --version
9.5.1
PS C:\Users\conno\Github\DefinitelyTyped> npm i --legacy-peer-deps
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 814 packages, and audited 815 packages in 14s

144 packages are looking for funding
  run `npm fund` for details

6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS C:\Users\conno\Github\DefinitelyTyped> npm test node

> definitely-typed@0.0.3 test
> node --require source-map-support/register node_modules/@definitelytyped/dtslint/ types node

dtslint@0.0.158
testing from 4.3 to 4.8 in C:\Users\conno\Github\DefinitelyTyped\types\node\ts4.8

Could not find implementations for the following rules specified in the configuration:
    no-import-default-of-export-equals
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

Error: 
C:\Users\conno\Github\DefinitelyTyped\types\node\ts4.8\dom-events.d.ts
  23:21  error  Type [T] is a single-element tuple type. You probably meant T[]  no-single-element-tuple-type

✖ 1 problem (1 error, 0 warnings)

    at testTypesVersion (C:\Users\conno\Github\DefinitelyTyped\node_modules\@definitelytyped\dtslint\src\index.ts:235:11)
    at runTests (C:\Users\conno\Github\DefinitelyTyped\node_modules\@definitelytyped\dtslint\src\index.ts:197:7)
    at main (C:\Users\conno\Github\DefinitelyTyped\node_modules\@definitelytyped\dtslint\src\index.ts:83:5)
```

**Comment by jakebailey** [comment]
tslint is no more.
