### ISSUE TITLE
dtslint "out of memory" during CI run of @types/openui5

### ISSUE THREAD

**Issue by akudev** [DefinitelyTyped/DefinitelyTyped#65580]
Hi,
the CI for our most recent type update failed with "out of memory" during the dtslint check, see https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6c5f965ded41fbc2a3766e95feefebe0ab1123cf/checks?check_suite_id=13008141821 and the below copy of the relevant part of the log.

We eventually succeeded by changing the TypeScript version in index.d.ts from 4.7 to 5.0 (because I read elsewhere that the version does affect memory usage), but this might happen again with another version of TS or our types, so I wanted to make you aware if the incident.

```
1> openui5 START
dtslint@0.0.160
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.

<--- Last few GCs --->

[2091:0x66d5420]   103350 ms: Scavenge (reduce) 2044.2 (2080.2) -> 2043.6 (2080.5) MB, 16.8 / 0.0 ms  (average mu = 0.129, current mu = 0.012) allocation failure 
[2091:0x66d5420]   105511 ms: Mark-sweep (reduce) 2044.7 (2080.7) -> 2043.5 (2080.7) MB, 2122.2 / 0.0 ms  (average mu = 0.122, current mu = 0.116) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb090e0 node::Abort() [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 2: 0xa1b70e  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 3: 0xce19d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 4: 0xce1d77 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 5: 0xe993e5  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 6: 0xe99ec6  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 7: 0xea[83](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6c5f965ded41fbc2a3766e95feefebe0ab1123cf/checks?check_suite_id=13008141821#step:6:84)ee  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 8: 0xea8e30 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 9: 0xeabdae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
10: 0xe6d2ea v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
11: 0x11e6196 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
12: 0x15d9e19  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
1> openui5 Out of memory: retrying
1> Restarting...
dtslint@0.0.160
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.

<--- Last few GCs --->

[2147:0x67b[84](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6c5f965ded41fbc2a3766e95feefebe0ab1123cf/checks?check_suite_id=13008141821#step:6:85)20]   106169 ms: Scavenge (reduce) 2044.4 (2080.5) -> 2043.8 (2080.7) MB, 10.4 / 0.0 ms  (average mu = 0.119, current mu = 0.019) allocation failure 
[2147:0x67b8420]   108349 ms: Mark-sweep (reduce) 2044.6 (2080.7) -> 2043.7 (2081.0) MB, 2157.0 / 0.0 ms  (average mu = 0.107, current mu = 0.095) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb0[90](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6c5f965ded41fbc2a3766e95feefebe0ab1123cf/checks?check_suite_id=13008141821#step:6:91)e0 node::Abort() [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 2: 0xa1b70e  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 3: 0xce19d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 4: 0xce1d77 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 5: 0xe9[93](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6c5f965ded41fbc2a3766e95feefebe0ab1123cf/checks?check_suite_id=13008141821#step:6:94)e5  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 6: 0xe[99](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6c5f965ded41fbc2a3766e95feefebe0ab1123cf/checks?check_suite_id=13008141821#step:6:100)ec6  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 7: 0xea83ee  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 8: 0xea8e30 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
 9: 0xeabdae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
10: 0xe6d022 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
11: 0xe6793c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
12: 0xe67a15 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
13: 0x10d03de v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
14: 0x10d0493 v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
15: 0x11dc5c5 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
16: 0x15d9e19  [/opt/hostedtoolcache/node/16.20.0/x64/bin/node]
1> openui5 Out of memory: failed


=== SUGGESTIONS ===



=== ERRORS ===



Error in openui5
Out of memory
{}
```

**Comment by jakebailey** [comment]
Old issue but based on the most recent runs, this doesn't seem to be happening anymore. https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/7725729419

**Comment by akudev** [comment]
@jakebailey  Well, as things happen, this is back in our internal integration builds. Interestingly, only on Windows.


```
[error] @ui5/dts-generator/runCheck: An error occurred Error: 
Internal error: The string parsing of the dtslint output found no errors although the output contained the term 'error' (1 times).
This is a hint that dtslint either encountered a general error (details below) or might have been updated and changed its format, so the parsing needs to be adapted.
The actual error message was:

<--- Last few GCs --->

[7456:00000187F418CA20]    61726 ms: Mark-sweep 2045.5 (2082.1) -> 2043.8 (2082.6) MB, 1005.6 / 0.0 ms  (average mu = 0.092, current mu = 0.015) allocation failure scavenge might not succeed
[7456:00000187F418CA20]    62774 ms: Mark-sweep (reduce) 2046.3 (2083.0) -> 2044.9 (2080.8) MB, 712.7 / 0.0 ms  (+ 77.2 ms in 18 steps since start of marking, biggest step 14.7 ms, walltime since start of marking 824 ms) (average mu = 0.164, current mu = 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7EE7E151F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+121999
 2: 00007FF7EE76B386 DSA_meth_get_flags+64118
 3: 00007FF7EE76C402 DSA_meth_get_flags+68338
 4: 00007FF7EF0A2C94 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF7EF08D25D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF7EEF3081C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF7EEF2D934 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF7EEF2B2B0 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF7EEF4FE36 v8::internal::Factory::NewFillerObject+214
10: 00007FF7EEC82545 v8::internal::DateCache::Weekday+1797
11: 00007FF7EF130971 v8::internal::SetupIsolateDelegate::SetupHeap+494417
12: 00007FF7EF0EEACB v8::internal::SetupIsolateDelegate::SetupHeap+224427
13: 00000187F5EE9EC0
    at getErrorDetails (file:///c:/tmp/workspace/master/sapui5.windows_host.validation/target/node-tools/dts-generator/dts-generator/dist/checkDtslint/check-dtslint.js:243:15)
    at checkDtslint (file:///c:/tmp/workspace/master/sapui5.windows_host.validation/target/node-tools/dts-generator/dts-generator/dist/checkDtslint/check-dtslint.js:97:26)
    at main (file:///c:/tmp/workspace/master/sapui5.windows_host.validation/target/node-tools/dts-generator/dts-generator/dist/runCheck.js:51:9)
Feb 06, 2024 3:25:03 AM com.sap.ui5.tools.node.util.ProcessUtil execute
INFO: Terminated process with exit code: 1. Reason: Process exited with an error: 1 (Exit value: 1)
```

Actually, I have to say that we only now switched from the npm package "dtslint" to "@definitelytyped/dtslint" in this internal test, so the issue might have been there a bit longer and only surfaced due to the switch.
At the same time, this test switched from TypeScript ^5.0.4 to ^5.3.3, so maybe this plays a role as well and we could temporarily mitigate by downgrading.

But that's not a solution.

**Comment by akudev** [comment]
@jakebailey  Well, as things happen, this is back in our internal integration builds. Interestingly, only on Windows.


```
[error] @ui5/dts-generator/runCheck: An error occurred Error: 
Internal error: The string parsing of the dtslint output found no errors although the output contained the term 'error' (1 times).
This is a hint that dtslint either encountered a general error (details below) or might have been updated and changed its format, so the parsing needs to be adapted.
The actual error message was:

<--- Last few GCs --->

[7456:00000187F418CA20]    61726 ms: Mark-sweep 2045.5 (2082.1) -> 2043.8 (2082.6) MB, 1005.6 / 0.0 ms  (average mu = 0.092, current mu = 0.015) allocation failure scavenge might not succeed
[7456:00000187F418CA20]    62774 ms: Mark-sweep (reduce) 2046.3 (2083.0) -> 2044.9 (2080.8) MB, 712.7 / 0.0 ms  (+ 77.2 ms in 18 steps since start of marking, biggest step 14.7 ms, walltime since start of marking 824 ms) (average mu = 0.164, current mu = 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
1: 00007FF7EE7E151F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+121999
2: 00007FF7EE76B386 DSA_meth_get_flags+64118
3: 00007FF7EE76C402 DSA_meth_get_flags+68338
4: 00007FF7EF0A2C94 v8::Isolate::ReportExternalAllocationLimitReached+116
5: 00007FF7EF08D25D v8::SharedArrayBuffer::Externalize+781
6: 00007FF7EEF3081C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
7: 00007FF7EEF2D934 v8::internal::Heap::CollectGarbage+4244
8: 00007FF7EEF2B2B0 v8::internal::Heap::AllocateExternalBackingStore+2000
9: 00007FF7EEF4FE36 v8::internal::Factory::NewFillerObject+214
10: 00007FF7EEC82545 v8::internal::DateCache::Weekday+1797
11: 00007FF7EF130971 v8::internal::SetupIsolateDelegate::SetupHeap+494417
12: 00007FF7EF0EEACB v8::internal::SetupIsolateDelegate::SetupHeap+224427
13: 00000187F5EE9EC0
```

Actually, I have to say that we only now switched from the npm package "dtslint" to "@definitelytyped/dtslint" in this internal test, so the issue might have been there a bit longer and only surfaced due to the switch.
At the same time, this test switched from TypeScript ^5.0.4 to ^5.3.3, so maybe this plays a role as well and we could temporarily mitigate by downgrading.

But that's not a solution.

**Comment by jakebailey** [comment]
The right place for this kind of report would be
