### ISSUE TITLE
`pnpm test <package>` does not work on aarch64-linux

### ISSUE THREAD

**Issue by samuela** [DefinitelyTyped/DefinitelyTyped#67484]
Running on eg ssh2,
```
[nix-shell:~/dev/DefinitelyTyped]$ pnpm test ssh2

> definitely-typed@0.0.3 test /Users/samuelainsworth/dev/DefinitelyTyped
> node --enable-source-maps node_modules/@definitelytyped/dtslint/ types "ssh2"

dtslint@0.0.196
Error: Cannot find module '/Users/samuelainsworth/.dts/typescript-installs/4.5/node_modules/typescript'
Require stack:
- /Users/samuelainsworth/dev/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.196_typescript@5.4.0-dev.20231122/node_modules/@definitelytyped/dtslint/dist/lint.js
- /Users/samuelainsworth/dev/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.196_typescript@5.4.0-dev.20231122/node_modules/@definitelytyped/dtslint/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at testDependencies (/Users/samuelainsworth/dev/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.196_typescript@5.4.0-dev.20231122/node_modules/@definitelytyped/dtslint/src/lint.ts:89:29)
    at lint (/Users/samuelainsworth/dev/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.196_typescript@5.4.0-dev.20231122/node_modules/@definitelytyped/dtslint/src/lint.ts:30:20)
    at testTypesVersion (/Users/samuelainsworth/dev/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.196_typescript@5.4.0-dev.20231122/node_modules/@definitelytyped/dtslint/src/index.ts:211:15)
    at runTests (/Users/samuelainsworth/dev/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.196_typescript@5.4.0-dev.20231122/node_modules/@definitelytyped/dtslint/src/index.ts:181:7)
    at main (/Users/samuelainsworth/dev/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.196_typescript@5.4.0-dev.20231122/node_modules/@definitelytyped/dtslint/src/index.ts:88:5)
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by jakebailey** [comment]
I don't think this has to do with it being arm64; 4.5 just dropped out of support so you may just want to ensure your root package is up to date with a `pnpm i --filter .`.

**Comment by jakebailey** [comment]
As of a few weeks ago, a new method is used to pull typescript versions, so this is definitely fixed (if there was a bug at all)
