### ISSUE TITLE
pnpm test errors while loading rule '@definitelytyped/npm-naming'

### ISSUE THREAD

**Issue by MatijaSi** [DefinitelyTyped/DefinitelyTyped#67921]
To reproduce first make a fork and then:

```
git clone --sparse --filter=blob:none https://github.com/MatijaSi/DefinitelyTyped.git repro
cd repro
git sparse-checkout add types/base64-js
pnpm install
pnpm test base64-js
```

Errors with:

```
> definitely-typed@0.0.3 test C:\Users\Matija\Documents\code3\repro
> node --enable-source-maps node_modules/@definitelytyped/dtslint/ types "base64-js"

dtslint@0.1.1
TypeError: Error while loading rule '@definitelytyped/npm-naming': Cannot read properties of null (reading 'error')
Occurred while linting C:\Users\Matija\Documents\code3\repro\types\base64-js\index.d.ts
    at getNpmInfo (C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\@definitelytyped+dts-critic@0.0.197_typescript@5.4.0-dev.20231218\node_modules\@definitelytyped\dts-critic\index.ts:197:12)
    at dtsCritic (C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\@definitelytyped+dts-critic@0.0.197_typescript@5.4.0-dev.20231218\node_modules\@definitelytyped\dts-critic\index.ts:81:19)
    at create (C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\@definitelytyped+eslint-plugin@0.0.203_@typescript-eslint+eslint-plugin@6.14.0_@typescript-es_6g3ync7ca42pmjmcn5riyjnfdi\node_modules\@definitelytyped\eslint-plugin\src\rules\npm-naming.ts:139:31)
    at Object.create (C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\@typescript-eslint+utils@6.14.0_eslint@8.56.0_typescript@5.4.0-dev.20231218\node_modules\@typescript-eslint\utils\src\eslint-utils\RuleCreator.ts:102:14)
    at createRuleListeners (C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:895:21)
    at C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:1066:110
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:1003:34)
    at Linter._verifyWithoutProcessors (C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:1355:31)
    at Linter._verifyWithConfigArray (C:\Users\Matija\Documents\code3\repro\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:1807:21)
 ELIFECYCLE  Test failed. See above for more details.
```

Also fails with other packages, not only with base64-js.

**Versions**:

- node: v21.4.0
- pnpm: 8.12.1
- typescript: 5.4.0-dev.20231218

**Comment by jakebailey** [comment]
I cannot reproduce this. Can you try clean installing?

**Comment by MatijaSi** [comment]
I tried also from original repository, not fork:

```
git clone https://github.com/DefinitelyTyped/DefinitelyTyped.git repro2 --sparse --filter=blob:none
cd .\repro2\
git sparse-checkout add types/base64-js
pnpm install --registry=https://registry.npmjs.org/
pnpm test base64-js
```

I got same error while loading npm-naming.

And if I clone the full repository:

```
git clone https://github.com/DefinitelyTyped/DefinitelyTyped.git repro3
cd .\repro3\
pnpm install --registry=https://registry.npmjs.org/
pnpm test base64-js
```

Still the same error.

Maybe it's windows specific? I will try on linux later.

**Comment by jakebailey** [comment]
If you run just `node`, then write `process.env` in the REPL, does it return `null` or an object with values?

**Comment by jakebailey** [comment]
dts-critic@0.0.197 is also a version behind, so you're not up to date.

**Comment by MatijaSi** [comment]
I tried running:

```
pnpm up
pnpm up --dev
```

Which updated dts-critic. Running test still fails with practically same error:

```
pnpm test base64-js

> definitely-typed@0.0.3 test C:\Users\Matija\Documents\code3\repro2
> node --enable-source-maps node_modules/@definitelytyped/dtslint/ types "base64-js"

dtslint@0.1.2
TypeError: Error while loading rule '@definitelytyped/npm-naming': Cannot read properties of null (reading 'error')
Occurred while linting C:\Users\Matija\Documents\code3\repro2\types\base64-js\index.d.ts
    at getNpmInfo (C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\@definitelytyped+dts-critic@0.0.198_typescript@5.3.3\node_modules\@definitelytyped\dts-critic\index.ts:197:12)
    at dtsCritic (C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\@definitelytyped+dts-critic@0.0.198_typescript@5.3.3\node_modules\@definitelytyped\dts-critic\index.ts:81:19)
    at create (C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\@definitelytyped+eslint-plugin@0.0.204_@typescript-eslint+eslint-plugin@6.15.0_@typescript-es_y7fhe7aae2e46vjiuuk3y3ok6e\node_modules\@definitelytyped\eslint-plugin\src\rules\npm-naming.ts:139:31)
    at Object.create (C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\@typescript-eslint+utils@6.15.0_eslint@8.56.0_typescript@5.3.3\node_modules\@typescript-eslint\utils\src\eslint-utils\RuleCreator.ts:102:14)
    at createRuleListeners (C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:895:21)
    at C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:1066:110
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:1003:34)
    at Linter._verifyWithoutProcessors (C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:1355:31)
    at Linter._verifyWithConfigArray (C:\Users\Matija\Documents\code3\repro2\node_modules\.pnpm\eslint@8.56.0\node_modules\eslint\lib\linter\linter.js:1807:21)
```

`process.env` returns object, which looks as expected:

```
{
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\Matija\\AppData\\Roaming',
  ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
  ChocolateyLastPathUpdate: '133159145101914385',
  ChocolateyToolsLocation: 'C:\\tools',
  CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_19680_EJWRPCBTQCXQVHBX',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  ...
}
```

**Comment by PCOffline** [comment]
Running into the same issue, I am using `npm`, though.

**Comment by PCOffline** [comment]
Will try on macOS later on

**Comment by PCOffline** [comment]
Update: in macOS, this error does not occur.

**Comment by jakebailey** [comment]
I must have misread the line number, this is more to do with the command failing for some reason and netting an undefined result. I'll look at this when I have some time, but you will probably have the most success working on DT if you're doing so within WSL.

**Comment by jakebailey** [comment]
I fixed this in https://github.com/microsoft/DefinitelyTyped-tools/pull/917 and can confirm that it fixed the test case provided in the original issue. Sorry for the wait!
